### PR TITLE
model builders with constructors, test suites, API cleanup

### PR DESCRIPTION
**Pull request by UnsungHero97**
**BREAKING CHANGES**

Renamed things:
- `FullyQualifiedName` > `FQN`
- `AuthorizationApi` > `AuthorizationsApi`
- `AppApi`
  - `getApps()` > `getAllApps()`
  - `getAppByName()` > `getApp()`
  - `getAppTypeByFqn()` > `getAppType()`
  - `getAppTypesForAppTypeIds()` > `getAppTypes()`
  - `getConfigurations` > `getAppConfigs()`
- `AuthorizationsApi`
  - `checkAuthorizations()` > `getAuthorizations()`
- `DataApi`
  - `deleteEntitiesAndNeighbors()` > `deleteEntityAndNeighborData()`
  - `deleteEntitySet()` > `deleteEntitySetData()`
- `EntityDataModelApi`
  - `addDstEntityTypeToAssociationType()` > 
`addDestinationEntityTypeToAssociationType()`
  - `addSrcEntityTypeToAssociationType()` > 
`addSourceEntityTypeToAssociationType()`
  - `removeDstEntityTypeFromAssociationType()` > `removeDestinationEntityTypeFromAssociationType()`
  - `removeSrcEntityTypeFromAssociationType()` > `removeSourceEntityTypeFromAssociationType()`
- `OrganizationsApi`
  - `addAutoApprovedEmailDomains()` > `addDomainsToOrganization()`
  - `addConnections()` > `addConnectionsToOrganization()`
  - `getAllMembers()` > `getOrganizationMembers()`
  - `getAllRoles()` > `getOrganizationRoles()`
  - `getAllUsersOfRole()` > `getUsersWithRole()`
  - `removeAutoApprovedEmailDomains()` > `removeDomainsFromOrganization()`
- `PersistentSearchApi`
  - `loadPersistentSearches()` > `getPersistentSearches()`
- `SearchApi`
  - `executeSearch()` > `searchEntitySetData()` (new)

Replaced api functions:
- `AppApi`
  - `getAppTypeByFqn()` replaced by `getAppType()`
- `DataApi`
  - `deleteEntity()` replaced by `deleteEntityData()` 
  - `getEntity()` replaced by `getEntityData()`
  - `replaceEntityData()` replaced by `updateEntityData()`
  - `replaceEntityInEntitySet()` replaced by `updateEntityData()`
  - `replaceEntityInEntitySetUsingFqns()` replaced by `updateEntityData()`

Removed api functions:
- `AppApi`
  - `createApp()`
  - `createAppType()`
  - `deleteApp()`
  - `deleteAppType()`
  - `addAppTypeToApp()`
  - `removeAppTypeFromApp()`
  - `updateAppEntitySetConfig()`
  - `updateAppConfigPermissions()`
  - `updateAppMetadata()`
  - `updateAppTypeMetadata()`
- `AuthorizationApi`
  - `getAccessibleObjects()`
- `DataApi`
  - `clearEntityFromEntitySet()`
  - `clearEntitySet()`
  - `getEntitySetDataFileUrl()`
- `DataIntegrationApi`
  - `createEntityAndAssociationData()`
- `EntityDataModelApi`
  - `createComplexType()`
  - `createEnumType()`
  - `deleteComplexType()`
  - `deleteEnumType()`
  - `forceDeletePropertyType()`
  - `forceRemovePropertyTypeFromEntityType()`
  - `getAllAvailableAssociationTypes()`
  - `getAllComplexTypes()`
  - `getAllEnumTypes()`
  - `getAllPropertyTypesInNamespace()`
  - `getAllSchemasInNamespace()`
  - `getAssociationTypeDetails()`
  - `getComplexType()`
  - `getComplexTypeHierarchy()`
  - `getEntityDataModelDiff()`
  - `getEntityDataModelVersion()`
  - `getEntityTypeHierarchy()`
  - `getEntityTypeId()`
  - `getEnumType()`
  - `getPropertyTypeId()`
  - `getSchemaFileUrl()`
  - `updateEntityDataModel()`
- `OrganizationsApi`
  - `addAutoApprovedEmailDomain()`
  - `getAutoApprovedEmailDomains()`
  - `removeAutoApprovedEmailDomain()`
  - `setAutoApprovedEmailDomains()`
  - `setConnections()`
- `PersistentSearchApi`
  - `updatePersistentSearchConstraints()`
  - `updatePersistentSearchExpiration()`
- `SearchApi`
  - `advancedSearchEntitySetData()`
  - `getEntitySets()`
  - `searchAssociationTypes()`
  - `searchEntityNeighbors()`
  - `searchEntityNeighborsBulk()`
  - `searchEntitySetData()` (old)
  - `searchEntityTypes()`
  - `searchEntityTypesByFQN()`
  - `searchOrganizations()`
  - `searchPropertyTypes()`
  - `searchPropertyTypesByFQN()`

Removed apis:
- `AnalysisApi`
- `FeedsApi`
- `LinkingApi`
- `RequestsApi`
- `SubscriptionApi`

Removed models:
- `DataEdgeKey`
- `LinkingEntitySet`
- `LinkingEntityType`
- `LinkingRequest`
- `Request`
- `RequestStatus`

Function signature changes:
- `EntityDataModelApi.updateSchema()`

Removed logic:
- `SearchApi`
  - `addIDField` - hits no longer have the extra `id` field, apps should use `openlattice.@id`

### CODE REVIEW

**Comment by solomontang** [comment]
> Removed apis:
> 
> * `AnalysisApi`
> * `FeedsApi`
> * `LinkingApi`
> * `RequestsApi`
> * `SubscriptionApi`
> 
> Removed models:
> 
> * `DataEdgeKey`
> * `LinkingEntitySet`
> * `LinkingEntityType`
> * `LinkingRequest`
> * `Request`
> * `RequestStatus`

This is a lot of removed functionality without replacements. Why are these being removed? AFAIK @katherinebernstein is actively working on an application that needs feeds and subscriptions.

**Comment by jokedurnez** [comment]
Same for LinkingApi, we're still hoping to get that linking-feedback app to be functional.

Also, why diverge from API-function names in the backend?  We've been trying to be consistent between python/R/java and I feel like that has greatly helped communication/debugging.

**Comment by katherinebernstein** [comment]
What was the reason for removing all these APIs? /which apps did you check to make sure they weren't in use?

**Comment by UnsungHero97** [comment]
Nobody but me uses the models; safe to remove.

`AnalysisApi`, `LinkingApi`, and `RequestsApi` are not used anywhere. When the time comes, they can be added back in, though I fully expect these APIs to change significantly.

`FeedsApi` and `SubscriptionApi` are used in one project, yes. `v0.74.0` can be used for now.

**Comment by UnsungHero97** [comment]
> What was the reason for removing all these APIs? /which apps did you check to make sure they weren't in use?

I've checked all apps. APIs that are not used anywhere, or only used in old / deprecated apps, are being removed.

**Comment by UnsungHero97** [comment]
> Same for LinkingApi, we're still hoping to get that linking-feedback app to be functional.
> 
> Also, why diverge from API-function names in the backend? We've been trying to be consistent between python/R/java and I feel like that has greatly helped communication/debugging.

**Pull request merged**
